spring.application.name=assistant
spring.datasource.url=jdbc:postgresql://localhost:5434/ai_assistant
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080
jwt.secret=your-very-long-secret-key-at-least-256-bits-long
jwt.expiration=86400000

spring.servlet.multipart.enabled=true

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

rag.chunk.size=1000
rag.chunk.overlap=200


file.upload-dir=uploads

groq.api.url=https://api.groq.com/openai/v1/chat/completions
groq.api.key=Paste your key here
groq.model=llama-3.3-70b-versatile

#embedding api
jina.api.key=Paste your key here
jina.api.model=jina-embeddings-v3
jina.api.url=https://api.jina.ai/v1/embeddings

logging.level.com.neeraj.assistant=DEBUG